Workaround missing debugging symbols.
Addressing
find-debuginfo: starting
Extracting debug info from 2 files
Error while writing index for `/root/rpmbuild/BUILD/edgetx-companion-2.11.0-build/BUILDROOT/usr/bin/edgetx-simulator': No debugging symbols
gdb-add-index: No index was created for /root/rpmbuild/BUILD/edgetx-companion-2.11.0-build/BUILDROOT/usr/bin/edgetx-simulator
gdb-add-index: [Was there no debuginfo? Was there already an index?]
Error while writing index for `/root/rpmbuild/BUILD/edgetx-companion-2.11.0-build/BUILDROOT/usr/bin/edgetx-companion': No debugging symbols
gdb-add-index: No index was created for /root/rpmbuild/BUILD/edgetx-companion-2.11.0-build/BUILDROOT/usr/bin/edgetx-companion
gdb-add-index: [Was there no debuginfo? Was there already an index?]
[...]
RPM build errors:
error: Empty %files file /root/rpmbuild/BUILD/edgetx-companion-2.11.0-build/edgetx-2.11.0/debugsourcefiles.list