Find miniz.h in /usr/include/miniz/miniz.h on Fedora 43+.
Addressing
companion/src/storage/minizinterface.h:26:10: fatal error: miniz.h: No such file or directory
   26 | #include "miniz.h"
      |          ^~~~~~~~~
compilation terminated.

(cherry picked from commit 56bbf6db92c17aa0b6209f82cfa48a25b99332b4)