Disable use of the Ninja generator.
Addressing
+ make -C /root/rpmbuild/BUILD/edgetx-companion-2.10.7-build/edgetx-2.10.7/redhat-linux-build native-configure
make: *** No rule to make target 'native-configure'.  Stop.
error: Bad exit status from /var/tmp/rpm-tmp.ZgdzFP (%build)

Following https://fedoraproject.org/wiki/Changes/CMake_ninja_default.

(cherry picked from commit 1c92ca209a960e6bbc8e0da26a264b4d7828c43b)
(cherry picked from commit cb5fdb2dd41c6695e0b5053aa449f0e26e018988)
(cherry picked from commit ef6edc5dd88d014b46386f2e0a91e638e0cad7dd)